name: Relay Schema bot

on:
  push:
    branches:
      - master
    paths:
      - 'schema.graphql'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jay-flow/relay-schema-bot@master
        with:
          token: ${{ secrets.PAT }}
          repo-url: https://github.com/Jay-flow/artifacts-pro

          # I don't want to enter it as below.
          # This is because it uses the secret value of the calling repository.
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
